export const COUNTRY_OPTIONS = [
  "Afghanistan",
  "Albania",
  "Algeria",
  "Andorra",
  "Angola",
  "Antigua and Barbuda",
  "Argentina",
  "Armenia",
  "Australia",
  "Austria",
  "Azerbaijan",
  "Bahamas",
  "Bahrain",
  "Bangladesh",
  "Barbados",
  "Belarus",
  "Belgium",
  "Belize",
  "Benin",
  "Bhutan",
  "Bolivia",
  "Bosnia and Herzegovina",
  "Botswana",
  "Brazil",
  "Brunei",
  "Bulgaria",
  "Burkina Faso",
  "Burundi",
  "Cabo Verde",
  "Cambodia",
  "Cameroon",
  "Canada",
  "Central African Republic",
  "Chad",
  "Chile",
  "China",
  "Colombia",
  "Comoros",
  "Congo",
  "Costa Rica",
  "Cote d'Ivoire",
  "Croatia",
  "Cuba",
  "Cyprus",
  "Czech Republic",
  "Democratic Republic of the Congo",
  "Denmark",
  "Djibouti",
  "Dominica",
  "Dominican Republic",
  "Ecuador",
  "Egypt",
  "El Salvador",
  "Equatorial Guinea",
  "Eritrea",
  "Estonia",
  "Eswatini",
  "Ethiopia",
  "Fiji",
  "Finland",
  "France",
  "Gabon",
  "Gambia",
  "Georgia",
  "Germany",
  "Ghana",
  "Greece",
  "Grenada",
  "Guatemala",
  "Guinea",
  "Guinea-Bissau",
  "Guyana",
  "Haiti",
  "Honduras",
  "Hungary",
  "Iceland",
  "India",
  "Indonesia",
  "Iran",
  "Iraq",
  "Ireland",
  "Israel",
  "Italy",
  "Jamaica",
  "Japan",
  "Jordan",
  "Kazakhstan",
  "Kenya",
  "Kiribati",
  "Kuwait",
  "Kyrgyzstan",
  "Laos",
  "Latvia",
  "Lebanon",
  "Lesotho",
  "Liberia",
  "Libya",
  "Liechtenstein",
  "Lithuania",
  "Luxembourg",
  "Madagascar",
  "Malawi",
  "Malaysia",
  "Maldives",
  "Mali",
  "Malta",
  "Marshall Islands",
  "Mauritania",
  "Mauritius",
  "Mexico",
  "Micronesia",
  "Moldova",
  "Monaco",
  "Mongolia",
  "Montenegro",
  "Morocco",
  "Mozambique",
  "Myanmar",
  "Namibia",
  "Nauru",
  "Nepal",
  "Netherlands",
  "New Zealand",
  "Nicaragua",
  "Niger",
  "Nigeria",
  "North Korea",
  "North Macedonia",
  "Norway",
  "Oman",
  "Pakistan",
  "Palau",
  "Palestine",
  "Panama",
  "Papua New Guinea",
  "Paraguay",
  "Peru",
  "Philippines",
  "Poland",
  "Portugal",
  "Qatar",
  "Romania",
  "Russia",
  "Rwanda",
  "Saint Kitts and Nevis",
  "Saint Lucia",
  "Saint Vincent and the Grenadines",
  "Samoa",
  "San Marino",
  "Sao Tome and Principe",
  "Saudi Arabia",
  "Senegal",
  "Serbia",
  "Seychelles",
  "Sierra Leone",
  "Singapore",
  "Slovakia",
  "Slovenia",
  "Solomon Islands",
  "Somalia",
  "South Africa",
  "South Korea",
  "South Sudan",
  "Spain",
  "Sri Lanka",
  "Sudan",
  "Suriname",
  "Sweden",
  "Switzerland",
  "Syria",
  "Taiwan",
  "Tajikistan",
  "Tanzania",
  "Thailand",
  "Timor-Leste",
  "Togo",
  "Tonga",
  "Trinidad and Tobago",
  "Tunisia",
  "Turkey",
  "Turkmenistan",
  "Tuvalu",
  "Uganda",
  "Ukraine",
  "United Arab Emirates",
  "United Kingdom",
  "United States",
  "Uruguay",
  "Uzbekistan",
  "Vanuatu",
  "Vatican City",
  "Venezuela",
  "Vietnam",
  "Yemen",
  "Zambia",
  "Zimbabwe",
] as const;

const COUNTRY_ALIASES: Record<string, string> = {
  sg: "Singapore",
  sgp: "Singapore",
  sin: "Singapore",
  ind: "India",
  in: "India",
  usa: "United States",
  us: "United States",
  unitedstatesofamerica: "United States",
  uk: "United Kingdom",
  gb: "United Kingdom",
  gbr: "United Kingdom",
  greatbritain: "United Kingdom",
  uae: "United Arab Emirates",
  ae: "United Arab Emirates",
  vn: "Vietnam",
  vnm: "Vietnam",
  th: "Thailand",
  tha: "Thailand",
  thai: "Thailand",
  thaai: "Thailand",
  my: "Malaysia",
  mys: "Malaysia",
  jp: "Japan",
  jpn: "Japan",
  kr: "South Korea",
  kor: "South Korea",
  tw: "Taiwan",
  twn: "Taiwan",
  cn: "China",
  chn: "China",
  hk: "Hong Kong",
  mo: "Macao",
};

// Maps canonical country name → search name variants for the restcountries.com API
export const MAP_SEARCH_ALIASES: Record<string, string[]> = {
  "United States": ["United States of America", "USA"],
  "United Kingdom": ["UK", "Great Britain"],
  "South Korea": ["Korea, Republic of", "Republic of Korea"],
  "North Korea": ["Korea, Democratic People's Republic of"],
  "Russia": ["Russian Federation"],
  "Vietnam": ["Viet Nam"],
  "Czechia": ["Czech Republic"],
  "Türkiye": ["Turkey"],
  "Iran": ["Iran, Islamic Republic of"],
  "Syria": ["Syrian Arab Republic"],
  "Laos": ["Lao People's Democratic Republic"],
  "Moldova": ["Moldova, Republic of"],
  "Bolivia": ["Bolivia, Plurinational State of"],
  "Tanzania": ["Tanzania, United Republic of"],
  "Venezuela": ["Venezuela, Bolivarian Republic of"],
};

const COUNTRY_LOOKUP = new Map(
  COUNTRY_OPTIONS.map((country) => [normalizeCountryKey(country), country] as const)
);

function normalizeCountryKey(value: string): string {
  return value.toLowerCase().replace(/[^a-z]/g, "");
}

export function normalizeCountryName(value: string): string {
  const trimmed = value.trim();
  if (!trimmed) return "";

  const normalizedKey = normalizeCountryKey(trimmed);
  return COUNTRY_ALIASES[normalizedKey] || COUNTRY_LOOKUP.get(normalizedKey) || trimmed;
}
